### ISSUE TITLE
Is Creating a DNS Server supposed to take this long.

### ISSUE THREAD

**Issue by ihaveaquestion64** [reswitched/PegaSwitch#10]
It has been about five minutes and it is still on this screen
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]

C:\Users\aidan>cd PegaSwitch-master

C:\Users\aidan\PegaSwitch-master>ruby rdns.rb $192.168.56.1
I, [2017-03-14T16:09:08.644173 #12936]  INFO -- : Starting RubyDNS server (v1.0.3)...
I, [2017-03-14T16:09:08.644173 #12936]  INFO -- : <> Listening on udp:0.0.0.0:53
I, [2017-03-14T16:09:08.659645 #12936]  INFO -- : <> Listening on tcp:0.0.0.0:53

Is it supposed to take this long?

**Comment by ieatcalcium** [comment]
It's already running.

If you're seeing "Listening" on your computer, it's running. You then have to go into your switches settings and change your DNS to point to your computer running the DNS server (in this case I'm guessing it is located at 192.168.56.1 port 53)

Go to the switch eshop or any other program with a web browser and it should connect.

**Comment by ihaveaquestion64** [comment]
Oh Ok, Thanks.

**Comment by ihaveaquestion64** [comment]
-
