### ISSUE TITLE
"TypeError: Object.values is not a function" when running "consoles"

### ISSUE THREAD

**Issue by wchill** [reswitched/pegaswitch#102]
![image](https://user-images.githubusercontent.com/3746651/37577982-d216499e-2af2-11e8-8818-d38ea27173a9.png)

**Comment by misson20000** [comment]
Are you running the latest node?

**Comment by wchill** [comment]
I was running 6.2.0 on my machine (didn't realize I hadn't updated in a long time). I tried running with node 9.8.0 and 8.10.0 and both of those just hang the ncurses UI on macOS, but running with `--disable-curses` seems to be fine.
