### ISSUE TITLE
What Do I change the DNS to and do I have to change the TCP/UDP ports?

### ISSUE THREAD

**Issue by ihaveaquestion64** [reswitched/PegaSwitch#11]
C:\Users\aidan\PegaSwitch-master>ruby rdns.rb $192.168.56.1
I, [2017-03-14T16:09:08.644173 #12936]  INFO -- : Starting RubyDNS server (v1.0.3)...
I, [2017-03-14T16:09:08.644173 #12936]  INFO -- : <> Listening on udp:0.0.0.0:53
I, [2017-03-14T16:09:08.659645 #12936]  INFO -- : <> Listening on tcp:0.0.0.0:53

With this, what settings would I change on my switch?

**Comment by SomeoneWeird** [comment]
Change the 'DNS Servers' on your switch to the IP of your computer.

**Comment by ihaveaquestion64** [comment]
Ok, but when the DNS server is less than fifteen characters, the switch adds more 0s to make up for that, is that ok?

**Comment by SomeoneWeird** [comment]
Yes :)

**Comment by ihaveaquestion64** [comment]
Ok, thx, I will try. Also, when I typed the command you gave for serve.py, it didn't work so I just typed serve.py to run it, would that work?

**Comment by SomeoneWeird** [comment]
You need to type `python serve.py`

**Comment by ihaveaquestion64** [comment]
I get this error when I type that.

C:\Users\aidan\PegaSwitch-master>python serve.py
'python' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\aidan\PegaSwitch-master>
