### ISSUE TITLE
Which IP should change the DNS to.

### ISSUE THREAD

**Issue by ihaveaquestion64** [reswitched/PegaSwitch#12]
Should it be my public IP or my local IP

**Comment by SomeoneWeird** [comment]
The IP address of the network your switch is connected to, so your local IP.

**Comment by ihaveaquestion64** [comment]
Should I put it for both Primary and Secondary?

**Comment by SomeoneWeird** [comment]
If it's setup correctly you should only need to set primary, but it doesn't hurt setting both.
