### ISSUE TITLE
Error when doing "npm install" on Linux Mint 18.3

### ISSUE THREAD

**Issue by dpronyaev** [reswitched/pegaswitch#120]
npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/pegaswitch/npm-debug.log

gyp: binding.gyp not found (cwd: /root/pegaswitch) while trying to load binding.gyp

**Comment by misson20000** [comment]
### npm ERR! _**Please include the following file with any support request:**_
### npm ERR! /root/pegaswitch/npm-debug.log

**Comment by dpronyaev** [comment]
[npm-debug.log](https://github.com/reswitched/pegaswitch/files/1967069/npm-debug.log)

**Comment by TuxSH** [comment]
@dpronyaev in `package.json`, remove the line containing `pty.js` and insert `    "node-pty": "^0.7.4",` instead, then reinstall pegaswitch. Please let us know if it works...

**Comment by misson20000** [comment]
Pull latest master and try again. Please re-open the issue if you're still having problems.
