### ISSUE TITLE
QueryMem Dump Unstable

### ISSUE THREAD

**Issue by shinyquagsire23** [reswitched/pegaswitch#13]
Regression caused by 1f0da11863233b3a73647d5d9c9f9cdd735d7d56 causes random crashes when querying memory addresses (with sc.memdump commented out). Commits prior to this have no such issue and are able to query the full address range.

**Comment by SomeoneWeird** [comment]
@daeken

**Comment by daeken** [comment]
This should be fixed as of the new code drop.  Please feel free to reopen if this issue pops back up.
