### ISSUE TITLE
(Request) will there ever be support for 4.2.0 and above?

### ISSUE THREAD

**Issue by Expertsonicgamer32x** [reswitched/pegaswitch#136]
idk if 4.2.0 even exist i think i got my switch after 6.0.0 so i was wondering if you guys can make support for above 4.1.0 to the latest firmware version (10.0.4 as of right now 6/30/2020)

**Comment by AuroraWright** [comment]
Support for 7.0.1 with Deja Vu will come eventually, but it's a very long term goal, as confirmed by @SciresM on our Discord server. There are no ETAs.

**Comment by Expertsonicgamer32x** [comment]
thanks for the answer
