### ISSUE TITLE
can not launch

### ISSUE THREAD

**Issue by tunip3** [reswitched/pegaswitch#18]
i i get this error when running
![screenshot from 2017-03-16 14-16-46](https://cloud.githubusercontent.com/assets/26260613/24000556/721ab568-0a53-11e7-907a-bb053a830bdd.png)

**Comment by jaisongreen** [comment]
@tunip3 it looks like it's saying that your address or port is already in use. You might have a process that is using that port already.

**Comment by Andoryuuta** [comment]
I suspect that it's DNSMasq listening on port 53. Every Ubuntu version 12.04+ runs DNSMasq for local DNS caching and resolving ([mentioned here by one of the Ubuntu devs](https://stgraber.org/2012/02/24/dns-in-ubuntu-12-04))

Run "sudo netstat -plntu" and see what is using the port.

**Comment by BtheDestroyer** [comment]
Had a similar issue. tl;dr: I screwed around with dnsmasq for like 5 minutes and it started working.

```
sudo npm start

> pegaswitch@1.0.0 start /home/bthedestroyer/Documents/SwitchHacking/PegaSwitch
> node start.js

There was an issue setting up DNS: bind EADDRINUSE 0.0.0.0:53
```
sudo netstat -plntu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      1463/dnsmasq    
....................................................................................................................................................
udp        0      0 127.0.1.1:53            0.0.0.0:*                           1463/dnsmasq 
```

Looks like dnsmasq is causing a problem. Killing the pid after removing dnsmasq from my /usr/sbin/ directory also killed my dns (obviously). I added the file back into /usr/sbin/ and ran `sudo /usr/sbin/dnsmasq` which started it and saw it took control of a ton of ports (probably like 15-20) so I killed it again. This time it restarted controlling far less ports (2 or 3) and my dns started working again. Best part is, now 53 was open meaning `sudo npm start` was successful. Checking now, `sudo netstat -plntu` doesn't even include dnsmasq, but I can still connect to websites and things.

**Comment by yeddish** [comment]
The easiest, to me, is to just stop network manager and kill dnsmasq:
```
service network-manager stop
killall dnsmasq
npm start
```
Then, when you're done, restart network manager
```
service network-manager start
```

**Comment by daeken** [comment]
This is a configuration issue on the machine, and not something we can really do anything about.  We would take a PR for better error handling, but this isn't a priority since this isn't end-user software.
