### ISSUE TITLE
Waiting for connection

### ISSUE THREAD

**Issue by schuler001** [reswitched/pegaswitch#20]
I can get my switch to connect to the capture page, and in the debug log it says that it starting, however in the REPL window it says that it is still waiting for a connection. What should I do to fix this? I am running on Ubuntu and I have node, python, and ruby installed.

![pegaswitch](https://cloud.githubusercontent.com/assets/24401683/24072145/8224b0b0-0bb8-11e7-83d1-f959653d442f.png)

**Comment by SomeoneWeird** [comment]
I presume you have opened the page on your switch? Does it connect properly?

**Comment by schuler001** [comment]
It connects, and I can see PegaSwitch by ReSwitched and a refresh button, but when I click the refresh button, it refreshes the page endlessly until the switch crashes, while in the debug log it says buffer not found.

![error](https://cloud.githubusercontent.com/assets/24401683/24072173/289d4074-0bb9-11e7-9549-6f5108cfaca9.png)

**Comment by SomeoneWeird** [comment]
Try hard resetting your switch. Hold the power button for ~15 seconds and let it restart and try again.

**Comment by schuler001** [comment]
It still gives the same result. In the debug it says it's starting but the REPL window is still waiting for a connection

**Comment by ioncodes** [comment]
Are you really in the same network as your Switch?

**Comment by schuler001** [comment]
Yeah. My computer is connected through Ethernet and my Switch is connected to the 2.4 GHz band

**Comment by ioncodes** [comment]
Are the ports open in your firewall? Or maybe some AV is blocking the connection?

**Comment by schuler001** [comment]
I opened the ports using the Ubuntu firewall, however decided to try the program with the firewall disabled, and now it seems to work. Thank you for the support

**Comment by ioncodes** [comment]
No problem.
