### ISSUE TITLE
Javascript REPL

### ISSUE THREAD

**Issue by misson20000** [reswitched/pegaswitch#26]
The current REPL does not have support for saving values and references to variables, and they must instead be copy/pasted. To add to that, some people are having issues copy/pasting out of the curses interface (holding shift works).

Also, much functionality is hidden and commented out. In order to enable this, the code must be changed, which involves reloading the webpage on the Switch.

If the REPL were changed to a Javascript prompt, it would solve all these problems and more. NPM packages and node.js libraries would be available, which, for example, would make it easier to save and load data to and from files.

**Comment by JoelLarson** [comment]
I would be willing to implement this feature but I do not have a Switch that I can test the code on. If you want to message me in Discord I will implement the feature with your feedback / knowledge of how the components connect.

**Comment by SomeoneWeird** [comment]
I did this and have a branch in our private repo, we decided not to merge it though because not many of us actually use the repl, and just store our scripts in external js files and execute them using `evalfile`. Do you still think we should do this @misson20000 ?

**Comment by misson20000** [comment]
I don't think this is something we still need to do.
