### ISSUE TITLE
Pegaswitch dns server

### ISSUE THREAD

**Issue by kupokappa** [reswitched/pegaswitch#29]
It seems as though the switch can't connect to the dns server pegaswitch makes, or the program doesn't set one up in the first place.

I'm running ubuntu, followed all the instructions. The terminal gives no errors, but the console doesn't connect to the dns I set up in the settings.

**Comment by gudenau** [comment]
This is also the case for me.

**Comment by robbix1206** [comment]
Under linux port equal or below 1024 are allowed to root user only
Try to put sudo before your command

**Comment by gudenau** [comment]
@robbix2016
I did run it as root.

**Comment by flewsea** [comment]
It maybe the firewall block it,i guess
