### ISSUE TITLE
"npm start" command not working

### ISSUE THREAD

**Issue by JustForNothing** [reswitched/PegaSwitch#3]
All command seem to work fine, but not "npm start":

![sans titre](https://cloud.githubusercontent.com/assets/18685185/23897675/538a6c2a-08ae-11e7-9bbd-eeba8f2f21bf.png)

Here is the log file:
https://transfer.sh/vllqB/npm-debug.log

**Comment by SomeoneWeird** [comment]
Did you run `npm install`?

**Comment by JustForNothing** [comment]
hum I reminder that I did it before unistalling node.js to, after reinstall it.
So I did it again and now it's working, sorry for that stupid issue.
