### ISSUE TITLE
Npm doesn't install

### ISSUE THREAD

**Issue by Molive-0** [reswitched/pegaswitch#30]
Running npm install on latest Pegaswitched crashes.
[2017-05-18T21_05_51_935Z-debugwelp.txt](https://github.com/reswitched/pegaswitch/files/1012622/2017-05-18T21_05_51_935Z-debugwelp.txt)
pls help

**Comment by QSonx** [comment]
looks like you might need the build tools.
`sudo apt-get install -y build-essential`

**Comment by Molive-0** [comment]
On windows?

**Comment by SomeoneWeird** [comment]
https://github.com/felixrieseberg/windows-build-tools
