### ISSUE TITLE
Npm install problem

### ISSUE THREAD

**Issue by Gasteclair** [reswitched/pegaswitch#31]
Error during npm install : 
![image](https://user-images.githubusercontent.com/21268663/27256215-aa5e23fc-53ae-11e7-916f-219167163ab2.png)
I try everything, I installed python, other versions of node, removed cache, run as administrator.
But it doesn't work

**Comment by Fruitboompje** [comment]
@Gasteclair I suggest you try using
`npm install --global --production windows-build-tools`
Let me know!

**Comment by Lusameme** [comment]
@Fruitboompje had the same issue installed fine but then got this error when i tried to start up
![error](https://user-images.githubusercontent.com/22406854/29097120-ff6e329e-7c4c-11e7-966f-4ccac4b5e74b.png)

**Comment by Haaroon** [comment]
Current build ran fine on npm 7.10.0 on OSX.

**Comment by Jhynjhiruu** [comment]
![image](https://user-images.githubusercontent.com/24824597/31094614-b9ce14ca-a7ad-11e7-9f0c-d49617558dba.png)
I get this error, even after ```npm install --global --production windows-build-tools```

**Comment by JoelLarson** [comment]
@Jhynjhiruu 

```
Error: listen EACCES 0.0.0.0:80
```

This means that something is already listening on port 80. On Windows, it is common that Skype is grabbing the port (otherwise some other software).

**Comment by Jhynjhiruu** [comment]
@JoelLarson 

> This means that something is already listening on port 80. On Windows, it is common that Skype is grabbing the port (otherwise some other software)
And how would I stop other software using it? Skype isn't active.

**Comment by JoelLarson** [comment]
@Jhynjhiruu Skype was just an example of a common Windows software that takes over port 80. Running this command in a command prompt with Administrator rights should give you an idea of where the problem is: `netstat -anb`

**Comment by SomeoneWeird** [comment]
@Jhynjhiruu mentioned he got this working in another issue. Closing.

**Comment by Jhynjhiruu** [comment]
Actually that was likely due to me switching to Ubuntu not doing something special on Windows.
