### ISSUE TITLE
DNS setup error

### ISSUE THREAD

**Issue by Jhynjhiruu** [reswitched/pegaswitch#38]
When running `sudo node start.js` under Ubuntu, after installing everything, I get an error: `There was an issue setting up DNS: bind EADDRINUSE 0.0.0.0:53`
How would I fix this? I'm not exactly a linux noob but I'm not sure how to fix this myself.

**Comment by JoelLarson** [comment]
`netstat -anp | grep ":53"`

**Comment by Jhynjhiruu** [comment]
That doesn't really help. I've already tried that, and whenever I try and kill dnsmasq it starts itself up again.

**Comment by P4ndaJ** [comment]
Same error for me. :(

**Comment by P4ndaJ** [comment]
I fix using --host argument with my ip

**Comment by cburwell** [comment]
https://askubuntu.com/a/233223a

Try this?

**Comment by P4ndaJ** [comment]
Try using _sudo node start.js --disable-curses --logfile debux.txt --host 127.0.0.1_  and then, set on internet connection the internal IP of your PC. This worked for me!

**Comment by d3m3vilurr** [comment]
@P4ndaJ is right. `--host` option will change listening ip. #24

**Comment by Jhynjhiruu** [comment]
Hmm. The Switch won't let me use 127.0.0.0 as the DNS... Halp mii

**Comment by P4ndaJ** [comment]
First thing: address is ```127.0.0.1``` . 

Second thing, you must add the internal IP of your PC, for example: 192.168.1.x

**Comment by Jhynjhiruu** [comment]
Nope. After putting "127.0.0.1" (or .0) into the primary DNS, the Switch says "The information you entered is incorrect."

**Comment by JoelLarson** [comment]
On the switch, 127.0.0.1 is going to resolve to itself which does not work. The switch needs to point to the DNS server that pegaswitch starts.

127.0.0.1 is usually the most common IP for resolving localhost, but the rest of 127.0.0.0/8 is not really used by default in my experience (it's defined as a loopback address range)

`--host` in PegaSwitch will change what IP address the DNS server listens on. You will most likely want to use `0.0.0.0` if you're unsure of networking (this address will listen to all traffic coming in). From there, you want your switch to point to the IP address of the machine running PegaSwitch.

**Comment by Jhynjhiruu** [comment]
That doesn't help.
My current situation is:
Running start.js with no additionall settings gives me an error saying 0.0.0.0:53 is in use.
Running it with --host 127.0.0.1 allows me to access the pegaswitch program, but I can't get my Switch to connect no matter what.
I'm on firmware 3.0.0 on my Switch, running Ubuntu 16.04 on the computer. Same WiFi network, no idea why it isn't working.

**Comment by P4ndaJ** [comment]
Can you post a screenshot of your switch internet settings please?

**Comment by Jhynjhiruu** [comment]
Not really.
`IP Address Settings: Automatic
DNS Settings: Manual
        Primary DNS: 192.168.000.012
        Secondary DNS: 192.168.000.224
Proxy Settings: Off`
Anything else you need?

**Comment by d3m3vilurr** [comment]
just use your device ip. (do not use localhost)
if you use the internal network, ip should be 10.x.x.x,172.x.x.x or 192.x.x.x
if you want to access outside of the internal network, you should port forward in the router configuration.

**Comment by Jhynjhiruu** [comment]
I tried my IP from whatismyip.com and my IP from ifconfig, and various IPs in the pegaswitch launch command, but I still can't get it to work.

**Comment by d3m3vilurr** [comment]
use result of `ifconfig`, not external ip.

**Comment by Jhynjhiruu** [comment]
Doesn't work. On Ubuntu, what could be stopping pegaswitch from listening on 0.0.0.0:53? If I could find out everything would probably work fine.

**Comment by P4ndaJ** [comment]
I did not understand it! To change from ```0.0.0.0:53``` to ```127.0.0.1```
 for example, just use the command ```--host```!

**Comment by misson20000** [comment]
You don't want to change your bind address (what `--host` changes) to 127.0.0.1. That will make the Switch unable to connect to the PegaSwitch DNS server. Unless your network configuration is especially strange and you know what you're doing, you probably don't need to touch `--host`. 

You need to stop whatever has already bound port 53 on 0.0.0.0. For some reason, a lot of people on Ubuntu seem to be running dnsmasq, which binds port 53. Here's a stack exchange thread on how to disable it: https://askubuntu.com/questions/233222/how-can-i-disable-the-dns-that-network-manager-uses

**Comment by d3m3vilurr** [comment]
@Jhynjhiru first you need find your ip address. like `ifconfig $(ip route| grep default | awk '{print $5}') | grep inet | head -n 1 | awk '{print $2}'`

then use `node server.js --host {ip addr}`
do not add `0.0.0.0:53`, do not use `127.0.0.1`. just use your computer ip address.

web service like whereismyip just return your external ip, and probably cannot help you.

**Comment by Jhynjhiruu** [comment]
Hm. Everything works fine now, and I didn't change anything, except restarting... Thanks for the help guys
.

**Comment by pplatoon** [comment]
I have problems showing the ip-dns that I should put on the switch. When I launch pegaswitch with sudo node start.js on the screen only frames but no information comes out. What is happening? any ideas? I followed all the steps and I have pegaswitch and libtransistor. use bash in windows 10
