### ISSUE TITLE
DNS does not setup

### ISSUE THREAD

**Issue by CAlexplayz** [reswitched/pegaswitch#48]
Hi is there anyone That can help me with this issue. 
There was an issue setting up DNS: bind EADDRINUSE 0.0.0.0:53

**Comment by misson20000** [comment]
Are you running Ubuntu? If so, see https://github.com/reswitched/pegaswitch/issues/38#issuecomment-334963492

**Comment by CAlexplayz** [comment]
Yes I am but dnsmasq is not installed on mine.

**Comment by CAlexplayz** [comment]
Shit how do I open it back up

**Comment by Dark-Mind** [comment]
This is what you need to do for Ubuntu to work

`sudo service systemd-resolved stop`

If that didn't work then try to find what is using port 53 using this command

`sudo lsof -i :53`

**Comment by Dark-Mind** [comment]
Now is it normal behavior that the internet connection stops working after you successfully run pegaswitch server?

Or is that a problem with Ubuntu too?

**Comment by misson20000** [comment]
It's not normal behaviour. It's probably because you killed systemd-resolved.

**Comment by bgoode2006** [comment]
I'm having this issue and I cant find a solution.

There was an issue setting up DNS: bind EACCES 0.0.0.0:53

Have already tried overriding host.
