### ISSUE TITLE
Error: listen EACCES 0.0.0.0:80

### ISSUE THREAD

**Issue by tommai78101** [reswitched/pegaswitch#49]
I have encountered an error, given with the following stack trace:

```
$ sudo node start.js
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at Server.setupListenHandle [as _listen2] (net.js:1327:19)
    at listenInCluster (net.js:1385:12)
    at doListen (net.js:1494:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

I am not entirely sure what to make of it. I'm in the process of installing PegaSwitch from scratch after updating to Ubuntu Xenial on WSL.

**Comment by misson20000** [comment]
You running Skype? If so, go to Options > Connection and turn off "Use port 80 and 443 for additional incoming connections"

**Comment by tommai78101** [comment]
I'm not even sure if I'm running Skype. But, just to make sure, I have opened Skype, went to Tools > Connection Options, unchecked "Use port 80 and 443 for additional incoming connections," quit Skype, then restart Skype, went back to Tools > Connection Options, and then verified the option has been unchecked, before quitting Skype for a second time. 

The Skype Settings have been changed since the Anniversary Update to the Creator's Update. I don't know if there will be any drastic changes for the upcoming Fall Creator's Update.

Upon launching WSL, it was stuck in a state where the title would say, "Select Bash for Windows". Closing the window, as well as attempting to kill the Bash process from the Task Manager wouldn't work. I ended up pressing CTRL+C to force quit it, which worked somehow. WSL then quit normally thereafter.

I then restart WSL, and did `sudo node start.js`, and it still throws the following stack trace:

```
$ sudo node start.js
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at Server.setupListenHandle [as _listen2] (net.js:1327:19)
    at listenInCluster (net.js:1385:12)
    at doListen (net.js:1494:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Any other steps that I can try?

**Comment by misson20000** [comment]
If you run `netstat -a -b -n` under a command prompt (not bash) with admin privileges I think it should show you what has port 80 bound. I can't test since I'm not running Windows right now.

**Comment by tommai78101** [comment]
Thanks, I did the following command, and I found out that `AlienwareAlienFXController.exe` is listening to port 80. Nothing is listening to port 443 though, so that's good.

It's a shame, but I'm not familiar with what Alienware AlienFX Controller is all about, nor have I been able to kill the process. I'll look it up, but if you have any information, please let me know.

**Comment by tommai78101** [comment]
Ok, further investigation reveals that the `AlienwareAlienFXController.exe` is not the only culprit. Apparently, another culprit is listening to port 80 when I killed the `AlienwareAlienFXController.exe` process. On Windows 10, if the user has or had enabled or used `Internet Information Services` in the past (IIS), there is a service called `World Wide Web Publishing Service` that is running locally on the machine, where it will listen to port 80. 

Disabling this service will stop the service from listening to port 80. But this service must be re-enabled for IIS to work properly, if the user intends to host a website or do some web management stuffs.

Disabling this service will also make PegaSwitch work correctly, and no longer throws an exception on not being able to listen to port 80. That's all.

This resolves my issue, and therefore I will be closing this. Thanks.
