### ISSUE TITLE
Fails to install on windows 10.

### ISSUE THREAD

**Issue by Dwood15** [reswitched/pegaswitch#61]
Both npm and nodejs are running without issue.

I have installed the windows-build-tools globally prior to this.

![pegaswitch_fail](https://user-images.githubusercontent.com/8879021/33250728-7be47c0e-d2ef-11e7-8ad9-865390b8a22e.png)

Python is 2.7.

**Comment by Dwood15** [comment]
Looks like the issue is related to installing pty.js I recommend moving to node-pty instead. pty.js has not been updated for a year, whereas node-pty is being actively maintained.

**Comment by MonkeyWrench123** [comment]
Did you get beyond this?, I have tried the method above, but no luck on Windows 10

**Comment by Dwood15** [comment]
I haven't built the project on my main machine in ages, so very possible something changed.
