### ISSUE TITLE
Using loadNro on 3.0.0, get Error: [ 408, 0x80e16 "Not initialized in module RO userland" ]

### ISSUE THREAD

**Issue by Dwood15** [reswitched/pegaswitch#62]
Am I doing it wrong? 

Should I do something like: evalfile loadNro.js <libtransistor>.

I've already run SetupNew.js, and it seemed successful.

**Comment by misson20000** [comment]
Use the `runnro` command.

**Comment by Dwood15** [comment]
For anyone who finds this from googling it, the solution is to enable sdbcore (by either running 'enable sdbcore' in pega, or making a config.json in the same folder as start.js and entering "sdbcore": true in the config).

'enable sdbcore' wasn't working for me, so I had to manually add it to the config file. Once sdbcore is enabled, you'll need to disconnect your switch from the wifi connection that pega is running on, and then reconnect it. I did that by turning airplane mode off and on, then going back to wifi and reconnecting.

Anyway, feel free to message me or someone else for help getting your switch set up. Remember. you need either 3.0.0 firmware or 1.0.0.
