### ISSUE TITLE
Error Connecting to switch

### ISSUE THREAD

**Issue by cole444** [reswitched/pegaswitch#82]
It says this when it Trys to connect to my switch

starting. 
building stuff.
building stuff.
ERR [56]: TypeError null is not an object  (evaluating 'vr.track.kind')

**Comment by daeken** [comment]
What version is your Switch on?

**Comment by cole444** [comment]
4.1.0

**Comment by daeken** [comment]
That's why.  Pegaswitch only works up to 3.0.0.
