### ISSUE TITLE
When i try to load pegaswitch on WSL, It doesn't work.

### ISSUE THREAD

**Issue by wizardbob101** [reswitched/pegaswitch#89]
Everything went fine unti' i typed "sudo node start.js". I could navigate to the pegaswitch folder, run npm install, and then when i run the command it shows me this. Please help.
![image](https://user-images.githubusercontent.com/36247127/35945188-2250be9c-0c14-11e8-8977-ee0bbacd8a06.png)

**Comment by Dwood15** [comment]
Unfortunately, this bug report tells us nothing. What version of Pegaswitch did you run?

What Linux flavor?

**Comment by wizardbob101** [comment]
i used ubuntu and it is the latest version of pegaswitch, i checked

**Comment by roblabla** [comment]
You forgot to install build-essential before installing pegaswitch. https://reswitchedweekly.github.io/Development-Setup/

**Comment by wizardbob101** [comment]
i already installed it

**Comment by roblabla** [comment]
Did you run `npm install` again after installing it ?

**Comment by wizardbob101** [comment]
it was already instaled and than i ran nom again

**Comment by roblabla** [comment]
🤔 So does `npm install` succeed without reporting any issues ? What happens if you run `sudo node start.js --disable-curses` ?

**Comment by wizardbob101** [comment]
wait let me send a picture

**Comment by wizardbob101** [comment]
![image](https://user-images.githubusercontent.com/36247127/36343621-5283738c-13c3-11e8-9892-76071549850d.png)

**Comment by wizardbob101** [comment]
it works thanks for helping

**Comment by wizardbob101** [comment]
thanks it worked
