### ISSUE TITLE
Please Help (sry)

### ISSUE THREAD

**Issue by ihaveaquestion64** [reswitched/PegaSwitch#9]
First, I used CD to go into the pegaswitch-master folder, and than typed, npm install. After that, I typed pip2 install flask but it gave the following message.

'pip2' is not recognized as an internal or external command,
operable program or batch file.

After this, I decided to skip that step and try to do the rubydns part. When I typed it in without starting the Command line with ruby, it gave me another error. When I tried to do it by running the command line by ruby, it said error loading file. 

What did I do wrong? Sorry to trouble you, im a bit of a newbie.

Ruby DNS error when running with Ruby:
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]

C:\Users\aidan>cd PegaSwitch-master

C:\Users\aidan\PegaSwitch-master>ruby rdns.rb $192.168.56.1
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rubydns (LoadError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from rdns.rb:2:in `<main>'

C:\Users\aidan\PegaSwitch-master>cd Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in
The filename, directory name, or volume label syntax is incorrect.

C:\Users\aidan\PegaSwitch-master>

Pip2 Install Flask Error:

C:\Users\aidan\PegaSwitch-master>pip2 install flask
'pip2' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\aidan\PegaSwitch-master>

**Comment by Andoryuuta** [comment]
The ruby error is because you haven't installed the rubydns gem yet. Make sure you run **`"gem install rubydns"`** first.

Also, assuming you don't have multiple versions of python, try running **`"pip install flask"`** .

**Comment by ihaveaquestion64** [comment]
Ok, thank you very much, I will try that right now :)

**Comment by ihaveaquestion64** [comment]
When I type Pip Install Flask without the two I get this message.

C:\Users\aidan\PegaSwitch-master>pip install flask
'pip' is not recognized as an internal or external command,
operable program or batch file.

Should I type it in start command prompt with ruby instead?

**Comment by Graphicscore** [comment]
I think by default the pip script is not added to the windows environment path.

You have multiple options now

1. Try to go into your python directory and run pip from there
```
cd  C:\[pythondir]\scripts
pip
```

2. Add the script folder to your environment path
```
Press [win key] + Pause
Advanced settings
System variables
Append ;C:\PYTHON_DIR\Scripts to the end of Path variable
Restart console
```

3. Try using the -m parameter to tell python you would like it to retrieve pip from the scripts folder
```
python -m pip
```

**Comment by ihaveaquestion64** [comment]
I don't have pip anywhere in my python folder, I have no script folder there either.

**Comment by Graphicscore** [comment]
Maybe you have to install pip at all - You could try to follow the following instructions, cannot confirm though , I am on OSX https://pip.pypa.io/en/stable/installing/#do-i-need-to-install-pip

**Comment by ihaveaquestion64** [comment]
Well I found a website with a file .gy file that is supposed to install pip so I'm going to try that.

**Comment by ihaveaquestion64** [comment]
It worked!, I have a script folder with many files. Should I use pip2 in the install flask command or just pip?

**Comment by ihaveaquestion64** [comment]
Also, on NPM install I got this message, is it okay? I think it still installed.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by ihaveaquestion64** [comment]
I successfully installed flask with the command, but when I typed the rubydns command in both the Ruby folder and the PegaSwitch folder, I got this error C:\Ruby23-x64>gem install rubydns
'gem' is not recognized as an internal or external command,
operable program or batch file.
