### ISSUE TITLE
dumpArchives.js does not support firmware 1.0.0

### ISSUE THREAD

**Issue by Hikari-chin** [reswitched/pegaswitch#90]
Per commit f2a6761, PegaSwitch now supports 1.0.0. However, `usefulscripts/dumpArchives.js` does not function because it attempts to dump some system data archives that are non-existent, running into this error: `ERROR: [ 826, '0xe05 (TitleId not found in module NCM) ' ]`.

**Comment by roblabla** [comment]
https://github.com/reswitched/pegaswitch/pull/92 fixes it
