### ISSUE TITLE
Disable curses interface by default

### ISSUE THREAD

**Issue by roblabla** [reswitched/pegaswitch#93]
The curses interface causes an abundance of problem while being of virtually no use to the vast majority of the users. See: #89 #55 #64 and the tool-support channel on reswitched.

Instead of the `--disable-curses` flag, I propose we change it to an `--enable-curses`, and disable it by default.

**Comment by SomeoneWeird** [comment]
At least 2 of those issues are because of WSL, which the readme says 'works fine without curses' - I'd be cool disabling it by default when we detect windows or WSL

**Comment by edgan** [comment]
Curses also prevents cut and paste, which I find really annoying.

**Comment by wchill** [comment]
The interface also breaks on macOS Sierra (didn't test High Sierra because that OS is still so buggy) if running node >= 8

**Comment by SomeoneWeird** [comment]
I wrote the interface when I was still running Sierra (and upgraded to High Sierra when it came out) and it's been fine for me. Can you explain how it's broken for you?

**Comment by wchill** [comment]
Running node 8.10.0 or node 9.8.0 (installed via homebrew respectively using `brew install node@8` and `brew upgrade node` from my old 6.2.0 version), I ran `sudo node start.js` (explicitly using either node 8 or node 9) and what happens is the curses UI comes up with the REPL and Debug panes, but nothing else other than that. Both panes are blank. Exactly the same problem as described in #89.
