### ISSUE TITLE
Rohan always failing with NRO hash

### ISSUE THREAD

**Issue by Rinnegatamante** [reswitched/pegaswitch#95]
Trying to install HBL by plutoo, i noticed today that PegaSwitch was always getting stucked somewhere.
Tried to run the DNS server on my vps and it seems like there's something wrong in rohan.

Log of my DNS: https://pastebin.com/MqyyeFqp

I already contacted plutoo and he told me that's supposed to be a bug in rohan and he doesn't have any clue why it happens and suggested me to refer to you.

**Comment by iOS4all** [comment]
All issues now have been fixed.
If you try again now you'll be able to run hombrew launcher successfully.
Good luck and hopefully we can get gpu acceleration soon from you
